INSERT INTO COURSE (ID, NAME) VALUES (10001, 'Course');
INSERT INTO COURSE (ID, NAME) VALUES (10002, 'Course');
INSERT INTO COURSE (ID, NAME) VALUES (10003, 'Course');
INSERT INTO COURSE (ID, NAME) VALUES (10004, 'Course');